### ISSUE TITLE
Handle exceptions at "end of world"

### ISSUE THREAD

**Issue by rintcius** [precog/quasar#3226]
There are cases where bugs cause exceptions being thrown, such as in #3171.
Would be good to walk through the code at the "end of the world" in `repl` and `web` and make sure they are handled a bit better. E.g. in repl the following is shown right now:

```
(v26.1.7) 💪 $ select city, sum(pop) from extraSmallZips group by lower(city)
(v26.1.7) 💪 $ [error] (AeshProcess: 2) java.lang.RuntimeException: 1
java.lang.RuntimeException: 1
	at quasar.effect.Failure$.quasar$effect$Failure$$$anonfun$16(Failure.scala:104)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:94)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:94)
	at scalaz.NaturalTransformation$$anon$1.apply(NaturalTransformation.scala:19)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:57)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
```

Also, although the repl doesn't break, you can be tricked into thinking it did break, because it doesn't show a new prompt when this happens - you have to press `enter` to get a prompt.
We can handle this better by adding `Internal Error` together with the stacktrace, and by making sure it does show the prompt.

I haven't checked the behaviour of `web` but would be good to verify this too.

**Comment by djspiewak** [comment]
In web, I believe such errors will turn into generic 500 responses.
